name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Setup PostgreSQL
        uses: postgresql/setup-postgres@v2
        with:
          postgres-version: '11.7'
          postgresql-user: ${{ secrets.PG_USER }}
          postgresql-password: ${{ secrets.PG_PASSWORD }}
          postgresql-db: ${{ secrets.PG_DATABASE }}

      - name: Run unit tests
        run: npm test

      - name: Run the app
        run: |
          npm install
          npx sequelize-cli db:drop
          npx sequelize-cli db:create
          npx sequelize-cli db:migrate
          PORT=3000 npm start &
          sleep 5

      - name: Run integration tests
        run: |
          npm install cypress cypress-json-results
          npx cypress run

      # Uncomment the deploy steps when you're ready to deploy
      # - name: Deploy to staging
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   run: |
      #     echo "Deploying to staging environment"
      #     # Add your deployment commands here
      #     # Example: scp or rsync to copy files to the server
      #     # Example: ssh to the server and restart the application
