# CI/CD Pipeline Configuration

name: CI/CD Pipeline

# Trigger the workflow on every push to the 'main' branch
on:
  push:
    branches:
      - main

# Define the jobs for the workflow
jobs:
  # Job to build, test, deploy, and handle errors
  build_test_deploy_errorhandling:
    runs-on: ubuntu-latest

    # Define services needed for the job, in this case, a PostgreSQL database
    services:
      postgres:
        image: postgres:11.7
        env:
          POSTGRES_USER: ${{ secrets.PG_USER }}
          POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}
          POSTGRES_DB: ${{ secrets.PG_DATABASE }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    # Define steps to be executed in the job
    steps:
      # Step to checkout the repository code
      - name: Checkout repository code
        uses: actions/checkout@v3

      # Step to install project dependencies
      - name: Install dependencies
        run: npm ci

      # Step to lint the code
      - name: Lint code
        run: npm run lint

      # Step to run unit tests
      - name: Run unit tests
        run: npm test

      # Step to run the application
      - name: Run the app
        id: run-app
        run: |
          npm install
          npx sequelize-cli db:drop
          npx sequelize-cli db:create
          npx sequelize-cli db:migrate
          PORT=3000 npm start &
          sleep 5

      # Step to run integration tests using Cypress
      - name: Run integration tests
        run: |
          npm install cypress cypress-json-results
          npx cypress run

      # Step to deploy to production using Render
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}

      # Step to send Slack notification on failure
      - name: Slack Notification
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          channel: '#github-notifications'
          message: |
            Build and Deploy Status: ${{ job.status }}
            Job Name: ${{ github.job }}
            Workflow: ${{ github.workflow }}
            Commit Message: ${{ github.event.head_commit.message }}
            Branch: ${{ github.ref }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()  # Send notification only on job failure
